
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-09-28T15:49:00-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "60fb83e76f859e47dd81f178b9e306d0e536bc2d",
 "version": "1.19.9.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
