
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T19:18:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "622ed251ad59802921342dbf9a1a4c99673b3a74",
 "version": "v0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
