[tool.poetry]
name = "plot3d"
version = "1.4.1"
description = "Plot3D python utilities for reading and writing and also finding connectivity between blocks"
authors = ["Paht Juangphanich <paht.juangphanich@nasa.gov>"]

[tool.poetry.dependencies]
python = "^3.9.1"
matplotlib = "^3.3.1"
numpy = "*"
pandas = "*"
psutil = "*"
pydoe = "*"
diversipy = "*"
doepy = "*" 
dataclasses_json = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.2"]
build-backend = "poetry.masonry.api"    
