
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-05T11:01:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2474dab8d505dc7286cbcbf1988bfea5470a423",
 "version": "4.7.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
