[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "yaml2xbel"
authors = [{name = "Ngô Ngọc Đức Huy", email = "huyngo@disroot.org"}]
readme = "README.md"
classifiers = [
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)"
]
dependencies = ["pyyaml"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://sr.ht/~huyngo/yaml2xbel"
