
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-10T14:05:49+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8cf75dd4de07ddd0d96fd0b27be2a15dabb10f2",
 "version": "2.0.3-2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
