
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-03T16:33:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "18eb75dfa4d0e8b356fdc09111ba84e605112450",
 "version": "0.4.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
