# coding: utf-8

"""
    1Password Connect

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.2.1
    Generated by: https://openapi-generator.tech
"""
from onepasswordconnectsdk.models.item_urls import ItemUrls

class OPItemUrls(ItemUrls):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'primary': 'bool',
        'href': 'str',
        'label': 'str'
    }

    attribute_map = {
        'primary': 'primary',
        'href': 'u',
        'label': 'l'
    }

    def __init__(self, primary=None, href=None, label=None):  # noqa: E501
        """ItemUrls - a model defined in OpenAPI"""  # noqa: E501
        self._label = None

        if label is not None:
            self.label = label
        super().__init__(primary, href)

    @property
    def label(self):
        """Gets the label of this ItemUrls.  # noqa: E501


        :return: The label of this ItemUrls.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ItemUrls.


        :param label: The label of this ItemUrls.  # noqa: E501
        :type: str
        """

        self._label = label
