
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-12T11:11:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5ed2bbfd79fe4a192d25bb75cdc2ef2fbcfee3d",
 "version": "5.1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
