[tool.poetry]
name = "namen"
version = "0.3.2"
description = ""
authors = ["Dennis van Bohemen <dennis.van.bohemen@profit4cloud.nl>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
