
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-05T18:06:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e632cbaf5b8483af597355e524d4cb40a1cd436d",
 "version": "2021.10.05"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
