#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['thycotic', 'thycotic.secrets']

package_data = \
{'': ['*']}

install_requires = \
['dataclasses >= 0.6', 'requests >= 2.12.5']

setup(name='python-tss-sdk',
      version='1.0.1',
      description='The Thycotic Secret Server Python SDK',
      author='Adam Migus',
      author_email='adam@migus.org',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
