from typing import Any, Iterator
from vtelem.enums.primitive import Primitive as Primitive, get_fstring as get_fstring, get_size as get_size

def crc(data: bytes, size: int = ..., initial_val: int = ...) -> int: ...

class ByteBuffer:
    size: Any
    data: Any
    pos: int
    mutable: Any
    order: Any
    def __init__(self, data: bytearray = ..., mutable: bool = ..., size: int = ..., order: str = ...) -> None: ...
    def reset(self) -> None: ...
    def with_pos(self, pos: int = ...) -> Iterator[None]: ...
    def expand_to(self, size: int) -> None: ...
    def set_pos(self, pos: int) -> None: ...
    def advance(self, amount: int, inc_size: bool = ...) -> None: ...
    def get_pos(self) -> int: ...
    def fstring(self, inst: Primitive) -> str: ...
    @property
    def remaining(self) -> int: ...
    def can_read(self, inst: Primitive) -> bool: ...
    def read(self, inst: Primitive, chomp: bool = ...) -> Any: ...
    def read_bytes(self, count: int, chomp: bool = ...) -> bytes: ...
    def append(self, other: bytes, data_len: int = ...) -> int: ...
    def crc32(self, initial_val: int = ...) -> int: ...
    def write(self, inst: Primitive, data: Any) -> int: ...
