from typing import Any, Callable
from vtelem.daemon.synchronous import Daemon as Daemon

class TimeKeeper(Daemon):
    time_function: Any
    sleep_function: Any
    scalar: Any
    time: Any
    last_time_eval: Any
    slaves: Any
    def __init__(self, name: str, rate: float, real_scalar: float = ..., time_fn: Callable = ..., sleep_fn: Callable = ...) -> None: ...
    def iteration(self, *_, **__) -> None: ...
    def add_slave(self, slave: Any) -> None: ...
    def set_slaves(self) -> None: ...
    def scale(self, scalar: float) -> None: ...
    def sleep(self, amount: float) -> None: ...
