from . import DEFAULTS as DEFAULTS
from .byte_buffer import ByteBuffer as ByteBuffer
from typing import Any, Callable, Tuple
from vtelem.enums.primitive import Primitive as Primitive, PrimitiveValue as PrimitiveValue, default_val as default_val, get_size as get_size

LOG: Any
ChangeCallback = Callable[[Tuple[PrimitiveValue, float], Tuple[PrimitiveValue, float]], None]

class TypePrimitive:
    type: Any
    data: Any
    changed_cb: Any
    last_set: Any
    def __init__(self, instance: Primitive, changed_cb: ChangeCallback = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def add(self, data: PrimitiveValue, time: float = ...) -> bool: ...
    def set(self, data: PrimitiveValue, time: float = ...) -> bool: ...
    def get(self) -> PrimitiveValue: ...
    def size(self) -> int: ...
    def write(self, buf: ByteBuffer, pos: int = ...) -> int: ...
    def read(self, buf: ByteBuffer, pos: int = ..., chomp: bool = ...) -> PrimitiveValue: ...
    def buffer(self, order: str = ...) -> bytes: ...

def new_default(default: str, changed_cb: ChangeCallback = ...) -> TypePrimitive: ...
