name: Flake8

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Flake8
        run: |
          pip install flake8 flake8-docstrings
          flake8 .
