name: Safety

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Check requirements
        run: |
          pip install safety
          safety check -r requirements.txt -r dev-requirements.txt
