[tool.poetry]
name = "onepasswordconnectsdkopexe"
version = "0.1.5"
description = "Python SDK for 1Password Connect with OP.exe "
authors = ["MSF-OCB", "Ian Sollars", "Sebastien Batteur"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/MSF-OCB/connect-sdk-python_opexe"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/MSF-OCB/connect-sdk-python_opexe/issues"

[tool.poetry.dependencies]
python = "^3.7"
onepasswordconnectsdk = "^1.1.0"
six = "^1.16.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
