
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T14:17:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d7d3d7dc5da728e89b1b5f46e6864b36e222a56",
 "version": "0.29.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
