name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Black
        run: |
          pip install black
          black . --check
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Flake8
        run: |
          pip install flake8 flake8-docstrings
          flake8 .
  requirements:
    name: Check Requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Check requirements
        run: |
          pip install safety
          safety check -r requirements.txt -r dev-requirements.txt
  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - name: Mypy
        run: |
          pip install -r dev-requirements.txt
          mypy .
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test
        run: tox
  release:
    name: Python Semantic Release
    runs-on: ubuntu-latest
    concurrency: release
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
    needs:
      - black
      - flake8
      - requirements
      - mypy
      - test
