[tool.poetry]
name = "conntask_ni"
version = "0.1.3"
description = ""
authors = ["shachar_gal <gal.shachar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.21.1"
pandas = "^1.3.0"
scikit-learn = "^0.24.2"
nibabel = "^3.2.1"
scipy = "^1.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
