[tool.poetry]
name = "monaco"
version = "0.1.0"
description = "A python library for setting up, running, and analyzing Monte-Carlo simulations."
authors = ["Scott Shambaugh"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/scottshambaugh/monaco/"
repository = "https://github.com/scottshambaugh/monaco/"

[tool.poetry.dependencies]
python = "~3.9"
numpy = "^1.21"
scipy = "^1.7"
pathos = "^0.2.7"
matplotlib = "^3.3.0"
tqdm = "^4.0"
pandas = "^1.3.0"
psutil = "^5.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
coverage = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
