[tool.poetry]
name = "pypanzer"
version = "1.0.3"
description = "panzer tools for python language"
authors = ["于中华 <583512498@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
xmltodict = "^0.12.0"
requests = "^2.22.0"
emoji = "^1.2.0"
selenium = "^3.141.0"
loguru = "^0.4.1"
pymongo = "^3.9.0"
redis = "^3.5.3"
pymysql = "^0.9.3"
SQLAlchemy = "^1.3.9"
pandas = "1.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true