#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['codesec']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

entry_points = \
{'console_scripts': ['codesec = codesec.cdsc:main']}

setup(name='codesec',
      version='0.2.4',
      description='Generates code headers for your text files',
      author=None,
      author_email='Raeed Ahmed <ruahmed7868@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      entry_points=entry_points,
     )
