# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test_stuff": "00_data_loader.ipynb"}

modules = ["data.py"]

doc_url = "https://Hevia.github.io/fastclimate/"

git_url = "https://github.com/Hevia/fastclimate/tree/main/"

def custom_doc_links(name): return None
