
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-04T15:16:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa0c19002887bfb529cc45b621f6c71e4a927b26",
 "version": "2.2.1.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
