[build-system]
requires = [ "poetry>=0.12" ]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "protocol-lib"
version = "1.0.0"
description = "Protocols for better structural typing"
authors = [ "Joseph Egan <joseph.s.egan@gmail.com>" ]
license = "MIT"
repository = "https://github.com/eganjs/protocol-lib"
readme = "README.md"

  [tool.poetry.dependencies]
  python = "^3.6"
  typing-extensions = "^3.7.4.3"

  [tool.poetry.dev-dependencies]
  pytest = "^6"
  black = "^20.8b1"
  flake8 = "^3.8.4"
  isort = "^5.6"
  pyprojroot = "^0.2.0"
  toml = "^0.10.1"
  types-toml = "^0.10.0"
  jedi = "^0.17.2"

    [tool.poetry.dev-dependencies.mypy]
    git = "https://github.com/eganjs/mypy"
    branch = "fix-issubclass-for-protocol"
