[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Michael Schock <m@mjschock.com>"]
description = "The datagrep CLI."
name = "datagrep"
readme = "README.md"
version = "3.0.0"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.4.0"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^5.2"
toml-sort = "^0.19.0"

[tool.poetry.scripts]
datagrep = "datagrep.main:app"
dgp = "datagrep.platform.main:app"
