[tool.poetry]
name = "annhub_python"
version = "0.1.6"
description = "Main backend module, which is used for developing web-app logic and deploying AI model."
authors = ["ARI Technology <dung.ut@ari.com.vn>"]
readme = "README.md"
homepage = "https://github.com/ans-ari/annhub-python"
repository = "https://github.com/ans-ari/annhub-python"
classifiers = [
    "Operating System :: Microsoft :: Windows"
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"
fastapi = "0.68.1"
uvicorn = "0.11.1"
requests = "2.22.0"
loguru = "0.4.0"
pytest = "6.2.4"
joblib = "1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
