
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T11:11:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac22d66c7cc5bb701099d1cadd8f3ca1719ebc84",
 "version": "0.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
