[tool.poetry]
name = "volttron-server"
version = "0.1.1"
description = "Server component for VOLTTRON"
authors = ["C. Allwardt <craig.allwardt@pnnl.gov>"]
license = "Apache-2.0"
packages = [
    { include = "volttron" }
]

[tool.poetry.dependencies]
python = ">=3.6.2,<4"
# Allows version number to be dynamically created from the
# importlib_metadata for the wheel file.  If using python
# 3.8 or greater this module is part of the standard library
# as importlib.metadata.  
#
# See volttron/commands/__init__.py
importlib-metadata = {version = "^1.0", python = "<3.8"}
volttron-client = "^0.3.0"
#volttron-utils = { path="../volttron-utils", develop=true}
#volttron-client = { path="../volttron-client", develop = true}
wheel = "^0.36"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"
sphinx-autobuild = "^2021.3.14"
m2r2 = "^0.2.8"
pre-commit = "^2.13.0"
black = "^21.6b0"
pylint = "^2.9.3"
mypy = "^0.910"
toml = "^0.10.2"

[tool.poetry.scripts]
volttron = 'volttron.server.__main__:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
