from typing import Tuple
from vtelem.classes.udp_client_manager import UdpClientManager as UdpClientManager
from vtelem.daemon.command_queue import CommandQueueDaemon as CommandQueueDaemon
from vtelem.mtu import Host as Host
from vtelem.types.command_queue_daemon import ResultCbType as ResultCbType

def add_client(manager: UdpClientManager, data: dict) -> Tuple[bool, str]: ...
def remove_client(manager: UdpClientManager, data: dict) -> Tuple[bool, str]: ...
def list_client(manager: UdpClientManager, data: dict) -> Tuple[bool, str]: ...
def create_udp_client_commander(manager: UdpClientManager, daemon: CommandQueueDaemon, result_cb: ResultCbType = ..., command_name: str = ...) -> None: ...
