from typing import List, Optional, Tuple
from vtelem.enums.primitive import Primitive as Primitive, PrimitiveEncoder as PrimitiveEncoder, get_name as get_name
from vtelem.registry import Registry as Registry

class TypeRegistry(Registry[Primitive]):
    def __init__(self, initial_types: List[Tuple[str, Primitive]] = ...) -> None: ...
    def get_type(self, type_id: int) -> Optional[Primitive]: ...
    def describe(self, indented: bool = ...) -> str: ...

def get_default() -> TypeRegistry: ...
