[tool.poetry]
name = "omspy"
version = "0.0.0"
description = ""
authors = ["Ubermensch <uberdeveloper001@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.1.2"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
