[tool.poetry]
name = "guava_preconditions"
version = "0.1.0"
description = "A python version of guava's preconditions"
authors = ["Elliana <me@mause.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
