
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T13:47:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0026b708a932a8916fc1107861f7189a17e5fe2",
 "version": "0.4.77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
