from fivana.cloudtrailsdk.decorators.custom_tracker import CustomLogger as custom_logger
from fivana.cloudtrailsdk.decorators.exception_tracker import exception_logger
from fivana.cloudtrailsdk.decorators.api_gateway_tracker import cloudtrails_apigatweay