
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T12:14:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d893016299767ce9c0c41b5be4aab7fc14315a5",
 "version": "5.1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
