#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['radicale_auth_sh']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['argon2-cffi < 21.0.0', 'radicale >= 3.0.0', 'setuptools']

extras_require = \
{'dev': ['scriv[toml]', 'build'], 'test': ['pytest', 'pytest-cov']}

setup(name='radicale-auth-sh',
      version='0.1.0',
      description='Plugin radicale-auth-sh',
      author='Ashwin V. Mohanan',
      author_email='y4d71nsar@relay.firefox.com',
      url='https://codeberg.org/ashwinvis/radicale-auth-sh',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
