
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T16:42:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cebab39ea0a4bafae1df809b52369c957e99c680",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
