
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-02T22:49:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ba9e1f848f0e7860b7aaaf5c4cc669567905638",
 "version": "v0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
