
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-10T02:17:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "44e462deb0be04e08a21b1251160a5c0f645621a",
 "version": "0.3.dev2141"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
