# Generated by Django 3.2.5 on 2021-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_koldar_utils.django_toolbox.fields.ArrowField
import django_koldar_utils.django_toolbox.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', django_koldar_utils.django_toolbox.fields.ArrowField.ArrowField(auto_now_add=True)),
                ('updated_at', django_koldar_utils.django_toolbox.fields.ArrowField.ArrowField(auto_now=True)),
                ('username', models.CharField(default=None, help_text='Username of the user. Used in the authentication method. Must be unique,', max_length=255, unique=True)),
                ('email', models.EmailField(default=None, help_text='email address used for resetting the password', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='If true, the user can log and work withint the system. False otherwise.')),
                ('is_superuser', models.BooleanField(default=False, help_text='True if this user is an admin, False otherwise')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
            ],
            options={
                'db_table': 'django_cbim_general_service.AuthUser',
                'managed': True,
            },
            managers=[
                ('objects', django_koldar_utils.django_toolbox.managers.ExtendedUserManager()),
            ],
        ),
    ]
