variables:
  TUXPKG: tuxpkg

.dist:
  stage: build
  image: debian
  script:
    - apt-get update
    - apt-get install -qy auto-apt-proxy
    - apt-get install -qy --no-install-recommends make git flit
    - make dist
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

.rpm:
  stage: build
  image: fedora
  script:
    - dnf install -y dnf-plugins-core rpm-build
    - 'dnf builddep -y *.spec'
    - make rpm
  artifacts:
    paths:
      - dist/*.rpm

.deb:
  stage: build
  image: debian
  before_script:
    - apt-get update
    - apt-get install -qy auto-apt-proxy
    - apt-get build-dep -qy .
    - make deb
  artifacts:
    paths:
      - dist/*.deb

.repository:
  image: debian
  stage: publish
  script:
    - apt-get update
    - apt-get install --no-install-recommends -qy dpkg-dev apt-utils createrepo-c rpm gpg gpg-agent python3
    - ${TUXPKG} create-repo
  artifacts:
    paths:
      - dist/repo

.pypi:
  image: debian
  stage: publish
  script:
    - apt-get update
    - apt-get istall --no-install-recommends git flit
    - flit publish
