
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T12:50:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "859e5a39cae1c2e1614026806ff2d8eca9a176fa",
 "version": "v0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
