[tool.poetry]
name = "shec"
version = "0"  # This is set dynamically via current git tag.
description = "An unofficial Splunk HTTP Endpoint Collector client (and more)."
authors = ["Mark Beacom <m@beacom.dev>"]

[tool.poetry.dependencies]
python = "^3.6"
httpx = {extras = ["http2", "brotli"], version = "^0.19.0"}
tenacity = "^8.0.1"
fire = "^0.4.0"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"
mock = "^4.0.3"
coverage = "^5.5"
isort = "^5.9.3"
black = "^21.8b0"
pydocstyle = "^6.1.1"
pylint = "^2.10.2"
bandit = "^1.7.0"
safety = "^1.10.3"
poethepoet = "^0.10.0"

# Version Plugin Configuration
[tool.poetry-version-plugin]
source = "git-tag"

# Styling and linting Configurations
[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.pylint]
line_length = 120

# Build System Configuration
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
