# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Admin(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'status': 'int',
        'username': 'str',
        'password': 'str',
        'email': 'str',
        'permissions': 'list[AdminPermissions]',
        'filters': 'AdminFilters',
        'additional_info': 'str'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'username': 'username',
        'password': 'password',
        'email': 'email',
        'permissions': 'permissions',
        'filters': 'filters',
        'additional_info': 'additional_info'
    }

    def __init__(self, id=None, status=None, username=None, password=None, email=None, permissions=None, filters=None, additional_info=None):  # noqa: E501
        """Admin - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._status = None
        self._username = None
        self._password = None
        self._email = None
        self._permissions = None
        self._filters = None
        self._additional_info = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if status is not None:
            self.status = status
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if email is not None:
            self.email = email
        if permissions is not None:
            self.permissions = permissions
        if filters is not None:
            self.filters = filters
        if additional_info is not None:
            self.additional_info = additional_info

    @property
    def id(self):
        """Gets the id of this Admin.  # noqa: E501


        :return: The id of this Admin.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Admin.


        :param id: The id of this Admin.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this Admin.  # noqa: E501

        status:   * `0` user is disabled, login is not allowed   * `1` user is enabled   # noqa: E501

        :return: The status of this Admin.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Admin.

        status:   * `0` user is disabled, login is not allowed   * `1` user is enabled   # noqa: E501

        :param status: The status of this Admin.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def username(self):
        """Gets the username of this Admin.  # noqa: E501

        username is unique  # noqa: E501

        :return: The username of this Admin.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this Admin.

        username is unique  # noqa: E501

        :param username: The username of this Admin.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this Admin.  # noqa: E501

        Admin password. For security reasons this field is omitted when you search/get admins  # noqa: E501

        :return: The password of this Admin.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Admin.

        Admin password. For security reasons this field is omitted when you search/get admins  # noqa: E501

        :param password: The password of this Admin.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def email(self):
        """Gets the email of this Admin.  # noqa: E501


        :return: The email of this Admin.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Admin.


        :param email: The email of this Admin.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def permissions(self):
        """Gets the permissions of this Admin.  # noqa: E501


        :return: The permissions of this Admin.  # noqa: E501
        :rtype: list[AdminPermissions]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this Admin.


        :param permissions: The permissions of this Admin.  # noqa: E501
        :type: list[AdminPermissions]
        """

        self._permissions = permissions

    @property
    def filters(self):
        """Gets the filters of this Admin.  # noqa: E501


        :return: The filters of this Admin.  # noqa: E501
        :rtype: AdminFilters
        """
        return self._filters

    @filters.setter
    def filters(self, filters):
        """Sets the filters of this Admin.


        :param filters: The filters of this Admin.  # noqa: E501
        :type: AdminFilters
        """

        self._filters = filters

    @property
    def additional_info(self):
        """Gets the additional_info of this Admin.  # noqa: E501

        Free form text field  # noqa: E501

        :return: The additional_info of this Admin.  # noqa: E501
        :rtype: str
        """
        return self._additional_info

    @additional_info.setter
    def additional_info(self, additional_info):
        """Sets the additional_info of this Admin.

        Free form text field  # noqa: E501

        :param additional_info: The additional_info of this Admin.  # noqa: E501
        :type: str
        """

        self._additional_info = additional_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Admin, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Admin):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
