# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BackupData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'users': 'list[User]',
        'folders': 'list[BaseVirtualFolder]',
        'admins': 'list[Admin]',
        'version': 'int'
    }

    attribute_map = {
        'users': 'users',
        'folders': 'folders',
        'admins': 'admins',
        'version': 'version'
    }

    def __init__(self, users=None, folders=None, admins=None, version=None):  # noqa: E501
        """BackupData - a model defined in Swagger"""  # noqa: E501
        self._users = None
        self._folders = None
        self._admins = None
        self._version = None
        self.discriminator = None
        if users is not None:
            self.users = users
        if folders is not None:
            self.folders = folders
        if admins is not None:
            self.admins = admins
        if version is not None:
            self.version = version

    @property
    def users(self):
        """Gets the users of this BackupData.  # noqa: E501


        :return: The users of this BackupData.  # noqa: E501
        :rtype: list[User]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this BackupData.


        :param users: The users of this BackupData.  # noqa: E501
        :type: list[User]
        """

        self._users = users

    @property
    def folders(self):
        """Gets the folders of this BackupData.  # noqa: E501


        :return: The folders of this BackupData.  # noqa: E501
        :rtype: list[BaseVirtualFolder]
        """
        return self._folders

    @folders.setter
    def folders(self, folders):
        """Sets the folders of this BackupData.


        :param folders: The folders of this BackupData.  # noqa: E501
        :type: list[BaseVirtualFolder]
        """

        self._folders = folders

    @property
    def admins(self):
        """Gets the admins of this BackupData.  # noqa: E501


        :return: The admins of this BackupData.  # noqa: E501
        :rtype: list[Admin]
        """
        return self._admins

    @admins.setter
    def admins(self, admins):
        """Sets the admins of this BackupData.


        :param admins: The admins of this BackupData.  # noqa: E501
        :type: list[Admin]
        """

        self._admins = admins

    @property
    def version(self):
        """Gets the version of this BackupData.  # noqa: E501


        :return: The version of this BackupData.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this BackupData.


        :param version: The version of this BackupData.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BackupData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackupData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
