
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-09T15:55:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "76c5a9fd307e313c8e939ab790f8b60628b4ffc7",
 "version": "2021.10.09"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
