# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.api.maintenance_api import MaintenanceApi  # noqa: E501
from sftpgo_client.rest import ApiException


class TestMaintenanceApi(unittest.TestCase):
    """MaintenanceApi unit test stubs"""

    def setUp(self):
        self.api = MaintenanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dumpdata(self):
        """Test case for dumpdata

        Backup SFTPGo data as data provider independent JSON  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Retrieve the status of the active services  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        Get version details  # noqa: E501
        """
        pass

    def test_loaddata_from_file(self):
        """Test case for loaddata_from_file

        Restore SFTPGo data from a JSON backup file on the server  # noqa: E501
        """
        pass

    def test_loaddata_from_request_body(self):
        """Test case for loaddata_from_request_body

        Restore SFTPGo data from a JSON backup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
