# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.api.token_api import TokenApi  # noqa: E501
from sftpgo_client.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_token(self):
        """Test case for get_token

        Get an access token  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        invalidate the access token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
