# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.api.quota_api import QuotaApi  # noqa: E501
from sftpgo_client.rest import ApiException


class TestQuotaApi(unittest.TestCase):
    """QuotaApi unit test stubs"""

    def setUp(self):
        self.api = QuotaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_folder_quota_update(self):
        """Test case for folder_quota_update

        update the folder used quota limits  # noqa: E501
        """
        pass

    def test_get_folders_quota_scans(self):
        """Test case for get_folders_quota_scans

        Get the active quota scans for folders  # noqa: E501
        """
        pass

    def test_get_quota_scans(self):
        """Test case for get_quota_scans

        Get the active quota scans for users home directories  # noqa: E501
        """
        pass

    def test_quota_update(self):
        """Test case for quota_update

        update the user used quota limits  # noqa: E501
        """
        pass

    def test_start_folder_quota_scan(self):
        """Test case for start_folder_quota_scan

        start a new folder quota scan  # noqa: E501
        """
        pass

    def test_start_quota_scan(self):
        """Test case for start_quota_scan

        start a new user quota scan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
