#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hijri']

package_data = \
{'': ['*']}

setup(name='hijri',
      version='0.1.2',
      description='A package to fetch hijri date in Arabic',
      author='Rayan Alkhelaiwi',
      author_email='rayan@hey.com',
      url='https://rayan.dev',
      packages=packages,
      package_data=package_data,
     )
