
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T23:12:49-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "b885b08d6e770a1b85bd6edc4b7364a0afd9cb07",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
