from enum import IntEnum
from json import JSONEncoder
from typing import Any, List, Tuple, Type
from vtelem.classes import DEFAULTS as DEFAULTS
from vtelem.classes.user_enum import UserEnum as UserEnum, from_enum as from_enum
from vtelem.registry import Registry as Registry
from vtelem.registry.type import TypeRegistry as TypeRegistry

LOG: Any

class UserEnumEncoder(JSONEncoder):
    def default(self, o) -> dict: ...

class EnumRegistry(Registry[UserEnum]):
    def __init__(self, initial_enums: List[UserEnum] = ...): ...
    def get_enum(self, enum: UserEnum) -> Tuple[bool, int]: ...
    def add_from_enum(self, enum_class: Type[IntEnum]) -> Tuple[bool, int]: ...
    def add_enum(self, enum: UserEnum) -> Tuple[bool, int]: ...
    def describe(self, indented: bool = ...) -> str: ...
    def export(self, registry: TypeRegistry) -> bool: ...
