[tool.poetry]
name = "carly"
version = "0.12.0"
description = "A tool for putting messages into and collecting responses from Twisted servers using real networking"
authors = ["Chris Withers <chris@withers.org>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/cjw296/carly"

[tool.poetry.dependencies]
python = ">=3.6.7"
Twisted = ">=21.7"
attrs = "*"

[tool.poetry.dev-dependencies]
testfixtures = "^6.3"
autobahn = "^18.11"
coverage = "*"

[tool.carthorse]
version-from = "poetry"
when = [
  "version-not-tagged"
]
actions = [
   { run="poetry publish --username __token__ --password $PYPI_TOKEN"},
   { name="create-tag"},
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
