repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: debug-statements
  - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
  - id: isort
    additional_dependencies:
    - isort[pyproject]
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    exclude: tests
