
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-09T22:23:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f48d8b27dd0d2edba18bef1da22f7db5071f7c5",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
