[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "antichecked"
authors = [{name = "SoniEx2", email = "endermoneymod@gmail.com"}]
dynamic = ["version", "description"]
license = {file = "LICENSE"}
readme = "README.md"

[project.urls]
Homepage = "https://ganarchy.autistic.space/project/996ab435341f148cf2c246fe800f86b8cd416506"
Repository = "https://soniex2.autistic.space/git-repos/antichecked.git"
