# PEP 518: https://www.python.org/dev/peps/pep-0518/

[tool.isort]
profile = "black"

[tool.poetry]
name = "chargeamps"
version = "1.4.4"
readme = "README.md"
description = "Charge-Amps API bindings for Python"
authors = ["Jakob Schlyter <jakob@kirei.se>"]
license = "BSD-2-Clause"
repository = "https://github.com/kirei/python-chargeamps"
packages = [
    { include = "chargeamps" }
]
keywords = [
    "ev"
]
classifiers = [
    'License :: OSI Approved :: BSD License',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.2"
asyncio = "^3.4.3"
dataclasses-json = "^0.5.2"
isodate = "^0.6.0"
marshmallow = "^3.9.0"
PyJWT = "^2.1.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
pylama = "^7.7.1"
pytest = "^6.2.0"
pytest-black = "^0.3.12"
pytest-isort = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chargeamps = "chargeamps.cli:main"
