[tool.poetry]
name = "acron"
version = "0.1.8"
description = "Lightweight scheduler"
authors = ["Aitor Iturri <aitor.iturri@appgate.com>", "Thomas Cellerier <thomas.cellerier@appgate.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/appgate/acron"

[tool.poetry.dependencies]
python = "^3.8"
croniter = "^1.0.15"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"
mypy = "^0.910"
types-croniter = "^1.0.0"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
