
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T13:58:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d4a863ffb2342bc65b82aadbf54a8c5c46b065e",
 "version": "0.4.80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
