from cerberus import Validator as Validator
from pathlib import Path
from typing import Any, Type
from vtelem import PKG_NAME as PKG_NAME
from vtelem.schema import SchemaMap as SchemaMap, load_schema as load_schema, load_schema_dir as load_schema_dir

def package_schemas(pkg: str = ..., subdir: str = ...) -> Path: ...

class SchemaManager:
    schemas: Any
    def __init__(self, initial: SchemaMap = ...) -> None: ...
    def __getitem__(self, arg: str) -> Validator: ...
    def get(self, cls: Type) -> Validator: ...
    def add(self, path: Path, name: str = ..., **kwargs) -> Validator: ...
    def load_dir(self, path: Path, **kwargs) -> SchemaMap: ...
    def load_package(self, pkg: str = ..., subdir: str = ..., **kwargs) -> SchemaMap: ...
