
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-08T11:58:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "18cc50ddb188bba17486c5ae632ab7a355a59402",
 "version": "0.4.81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
