
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T21:24:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce73e781d35095af42e37e1afa6b646ac9616e9b",
 "version": "v11.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
