# Generated by Django 3.1.7 on 2021-06-10 20:23

from django.db import migrations, models
import shapeeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histor_id', models.CharField(max_length=80)),
                ('history_date', models.DateField(auto_now_add=True)),
                ('history_json', models.JSONField(default=shapeeditor.models.default_empty_json)),
            ],
        ),
    ]
