# Generated by Django 3.1.7 on 2021-06-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapeeditor', '0002_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='histor_id',
            new_name='history_id',
        ),
    ]
