#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

package_dir = \
{'': 'src'}

setup(name='greenws',
      version='0.1.0a6',
      description='WebSockets for gevent.',
      author=None,
      author_email='Auri <me@aurieh.me>',
      url=None,
      py_modules=['greenws'],
      package_dir=package_dir,
      python_requires='>=3.7',
     )
