
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T12:40:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff8441a7099191ead54911755f4220ad735cd702",
 "version": "2.0.0a16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
