name: CI

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8
    - name: Lint with isort
      run: |
        pipenv run isort -c .
    - name: Run tests without slow test functions
      if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged != true || matrix.python-version != '3.9'
      run: |
        pipenv run pytest --cov=lineflow --cov-report=xml tests
    - name: Run all tests
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && matrix.python-version == '3.9'
      run: |
        pipenv run pytest --cov=lineflow --cov-report=xml tests -m "slow or not slow"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      if: ${{ matrix.python-version == '3.9' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
