[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "django-clear-s2s"
version = "0.1.3"
description = ""
authors = ["Your Name <you@example.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2.6"
requests-pkcs12 = "^1.13"

[tool.poetry.dev-dependencies]


