[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel>=0.30.0",
    "Cython>=0.29.21,<3.0",
    "numpy==1.19.4",
    "dimod>=0.10.0.dev9,<0.11.0",
]
build-backend = "setuptools.build_meta"
