# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SSHBinding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'port': 'int',
        'apply_proxy_config': 'bool'
    }

    attribute_map = {
        'address': 'address',
        'port': 'port',
        'apply_proxy_config': 'apply_proxy_config'
    }

    def __init__(self, address=None, port=None, apply_proxy_config=None):  # noqa: E501
        """SSHBinding - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._port = None
        self._apply_proxy_config = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if port is not None:
            self.port = port
        if apply_proxy_config is not None:
            self.apply_proxy_config = apply_proxy_config

    @property
    def address(self):
        """Gets the address of this SSHBinding.  # noqa: E501

        TCP address the server listen on  # noqa: E501

        :return: The address of this SSHBinding.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this SSHBinding.

        TCP address the server listen on  # noqa: E501

        :param address: The address of this SSHBinding.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def port(self):
        """Gets the port of this SSHBinding.  # noqa: E501

        the port used for serving requests  # noqa: E501

        :return: The port of this SSHBinding.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this SSHBinding.

        the port used for serving requests  # noqa: E501

        :param port: The port of this SSHBinding.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def apply_proxy_config(self):
        """Gets the apply_proxy_config of this SSHBinding.  # noqa: E501

        apply the proxy configuration, if any  # noqa: E501

        :return: The apply_proxy_config of this SSHBinding.  # noqa: E501
        :rtype: bool
        """
        return self._apply_proxy_config

    @apply_proxy_config.setter
    def apply_proxy_config(self, apply_proxy_config):
        """Sets the apply_proxy_config of this SSHBinding.

        apply the proxy configuration, if any  # noqa: E501

        :param apply_proxy_config: The apply_proxy_config of this SSHBinding.  # noqa: E501
        :type: bool
        """

        self._apply_proxy_config = apply_proxy_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SSHBinding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SSHBinding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
