# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebDAVBinding(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'port': 'int',
        'enable_https': 'bool',
        'client_auth_type': 'int'
    }

    attribute_map = {
        'address': 'address',
        'port': 'port',
        'enable_https': 'enable_https',
        'client_auth_type': 'client_auth_type'
    }

    def __init__(self, address=None, port=None, enable_https=None, client_auth_type=None):  # noqa: E501
        """WebDAVBinding - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._port = None
        self._enable_https = None
        self._client_auth_type = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if port is not None:
            self.port = port
        if enable_https is not None:
            self.enable_https = enable_https
        if client_auth_type is not None:
            self.client_auth_type = client_auth_type

    @property
    def address(self):
        """Gets the address of this WebDAVBinding.  # noqa: E501

        TCP address the server listen on  # noqa: E501

        :return: The address of this WebDAVBinding.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this WebDAVBinding.

        TCP address the server listen on  # noqa: E501

        :param address: The address of this WebDAVBinding.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def port(self):
        """Gets the port of this WebDAVBinding.  # noqa: E501

        the port used for serving requests  # noqa: E501

        :return: The port of this WebDAVBinding.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this WebDAVBinding.

        the port used for serving requests  # noqa: E501

        :param port: The port of this WebDAVBinding.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def enable_https(self):
        """Gets the enable_https of this WebDAVBinding.  # noqa: E501


        :return: The enable_https of this WebDAVBinding.  # noqa: E501
        :rtype: bool
        """
        return self._enable_https

    @enable_https.setter
    def enable_https(self, enable_https):
        """Sets the enable_https of this WebDAVBinding.


        :param enable_https: The enable_https of this WebDAVBinding.  # noqa: E501
        :type: bool
        """

        self._enable_https = enable_https

    @property
    def client_auth_type(self):
        """Gets the client_auth_type of this WebDAVBinding.  # noqa: E501

        1 means that client certificate authentication is required in addition to HTTP basic authentication  # noqa: E501

        :return: The client_auth_type of this WebDAVBinding.  # noqa: E501
        :rtype: int
        """
        return self._client_auth_type

    @client_auth_type.setter
    def client_auth_type(self, client_auth_type):
        """Sets the client_auth_type of this WebDAVBinding.

        1 means that client certificate authentication is required in addition to HTTP basic authentication  # noqa: E501

        :param client_auth_type: The client_auth_type of this WebDAVBinding.  # noqa: E501
        :type: int
        """

        self._client_auth_type = client_auth_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebDAVBinding, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebDAVBinding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
