# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.api.defender_api import DefenderApi  # noqa: E501
from sftpgo_client.rest import ApiException


class TestDefenderApi(unittest.TestCase):
    """DefenderApi unit test stubs"""

    def setUp(self):
        self.api = DefenderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ban_time(self):
        """Test case for get_ban_time

        Returns the ban time for the specified IPv4/IPv6 address  # noqa: E501
        """
        pass

    def test_get_score(self):
        """Test case for get_score

        Returns the score for the specified IPv4/IPv6 address  # noqa: E501
        """
        pass

    def test_unban_host(self):
        """Test case for unban_host

        Removes the specified IPv6/IPv6 from the banned ones  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
