# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.models.data_provider_status import DataProviderStatus  # noqa: E501
from sftpgo_client.rest import ApiException


class TestDataProviderStatus(unittest.TestCase):
    """DataProviderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataProviderStatus(self):
        """Test DataProviderStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sftpgo_client.models.data_provider_status.DataProviderStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
