# coding: utf-8

"""
    SFTPGo

    SFTPGo REST API  # noqa: E501

    OpenAPI spec version: 2.4.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sftpgo_client
from sftpgo_client.models.ftp_passive_port_range import FTPPassivePortRange  # noqa: E501
from sftpgo_client.rest import ApiException


class TestFTPPassivePortRange(unittest.TestCase):
    """FTPPassivePortRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFTPPassivePortRange(self):
        """Test FTPPassivePortRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sftpgo_client.models.ftp_passive_port_range.FTPPassivePortRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
