
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T21:13:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fab51b590e008076c2493b10850ba69b475abef3",
 "version": "1.81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
