
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-03T06:43:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc6e7498af806fe851b4c0157612033b46c03176",
 "version": "2021.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
