# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class NotificationTestRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    json_payload: typing___Text = ...

    @property
    def http(self) -> type___HttpRequest: ...

    def __init__(self,
        *,
        http : typing___Optional[type___HttpRequest] = None,
        json_payload : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"http",b"http",u"request_type",b"request_type"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"http",b"http",u"json_payload",b"json_payload",u"request_type",b"request_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"request_type",b"request_type"]) -> typing_extensions___Literal["http"]: ...
type___NotificationTestRequest = NotificationTestRequest

class HttpRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class HeadersEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___HeadersEntry = HeadersEntry

    url: typing___Text = ...
    httpMethod: typing___Text = ...

    @property
    def headers(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        url : typing___Optional[typing___Text] = None,
        httpMethod : typing___Optional[typing___Text] = None,
        headers : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"headers",b"headers",u"httpMethod",b"httpMethod",u"url",b"url"]) -> None: ...
type___HttpRequest = HttpRequest

class HttpResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    response_code: builtin___int = ...
    response_body: typing___Text = ...

    def __init__(self,
        *,
        response_code : typing___Optional[builtin___int] = None,
        response_body : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"response_body",b"response_body",u"response_code",b"response_code"]) -> None: ...
type___HttpResponse = HttpResponse

class NotificationTestResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    success: builtin___bool = ...

    @property
    def http(self) -> type___HttpResponse: ...

    def __init__(self,
        *,
        success : typing___Optional[builtin___bool] = None,
        http : typing___Optional[type___HttpResponse] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"http",b"http",u"response_type",b"response_type"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"http",b"http",u"response_type",b"response_type",u"success",b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"response_type",b"response_type"]) -> typing_extensions___Literal["http"]: ...
type___NotificationTestResponse = NotificationTestResponse
