[tool.poetry]
name = "capella-console-client"
version = "0.7.7"
description = "Python SDK for api.capellaspace.com (search, order, download)"
authors = ["Thomas Beyer <thomas.beyer@capellaspace.com>"]
repository = "https://github.com/capellaspace/console-client"
documentation = "https://capella-console-client.readthedocs.io/"
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    # supported python versions
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering :: Image Processing",
]
keywords = [ "CapellaSpace", "Earth Observation", "Capella Console", "Synthetic Aperture Radar", "SAR" ]
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
capella-console-wizard = 'capella_console_client.cli.cccc:main'


[tool.poetry.dependencies]
python = "^3.6.2"
python-dateutil = "^2.8.1"
httpx = "^0.18.2"
retrying = "^1.3.3"
rich = "^10.5.0"
typer = "^0.3.2"
questionary = "^1.10.0"
tabulate = "^0.8.9"
Sphinx = {version = "^3.3", optional = true}
sphinx-rtd-theme = {version = "^0.5.0", optional = true}
sphinx-autobuild = {version = "^2020.9.1", optional = true}
sphinx-copybutton = {version = "^0.3.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.11.1", optional = true}

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinx-autobuild", "sphinx-copybutton", "sphinx-autodoc-typehints"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-httpx = "^0.12.0"
pytest-html = "^3.1.1"
coveralls = "^3.1.0"
black = "^21.6b0"
mypy = "^0.910"

[tool.black]
line-length = 88
target-version = [ "py36", "py37", "py38", "py39" ]
exclude = "((.eggs | .git | .pytype | .pytest_cache | build | dist))"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
