[tool.poetry]
name = "alimits"
version = "1.0.0"
description = "Provides asyncio storage and strategy implementations for the limits library."
authors = [
    "Elias Gabriel <me@eliasfgabriel.com>",
    "Laurent Savaete <laurent@where.tf>",
    "Ali-Akber Saifee <ali@indydevs.org>"
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/thearchitector/alimits"
documentation = "https://thearchitector.github.io/alimits"
keywords = ["limits", "rate limiting", "api", "asyncio", "fastapi", "aiohttp"]

[tool.poetry.dependencies]
python = "^3.7"
limits = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"
hiro = "^0.5.1"
pymemcache = "^3.5.0"
pdoc = "^8.0.0"
black = "^21.9b0"
isort = "^5.9.3"
aredis = "^1.1.8"
mypy = "^0.910"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
show_column_numbers = true
follow_imports = "silent"
warn_unreachable = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
