SERVICES_EXCHANGE = 'services'
SERVICE_STARTUP_ROUTING_KEY = 'startup'
SERVICE_SHUTDOWN_ROUTING_KEY = 'shutdown'

DATABASE_EXCHANGE = 'database'
DATABASE_CME_INSERTED = 'db_cme_inserted'
DATABASE_DAILY_INSERTED = 'db_daily_inserted'
