
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-05T09:25:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22d65d2129b774af6716dbdc12c76e7f9fd4240a",
 "version": "0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
