[tool.poetry]
name = "datatoolkit"
version = "0.0.1"
description = ""
authors = ["Humberto STEIN SHIROMOTO <h.stein.shiromoto@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
bokeh = "^2.4.0"
Deprecated = "^1.2.13"
numpy = "^1.21.2"
pandas = "^1.3.3"
scipy = "^1.7.1"
seaborn = "^0.11.2"
statsmodels = "^0.13.0"
typeguard = "^2.12.1"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"
icecream = "^2.1.1"
ipykernel = "^6.4.1"
pytest = "^6.2.5"
rope = "^0.20.1"
twine = "^3.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
