[tool.poetry]
name = "namen"
version = "0.3.0"
description = ""
authors = ["Dennis van Bohemen <Dennis.Van.Bohemen@topicus.nl>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
