[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["TheFarGG", "Genofield"]
description = ""
name = "PyTweet"
version = "1.0.0"
[tool.poetry.dependencies]
oauth = "^1.0.1"
python = "^3.8"
requests-oauthlib = "^1.3.0"
[tool.poetry.dev-dependencies]
