channels:
- defaults
- http://ssb.stsci.edu/astroconda
dependencies:
- astropy==4.0.2
- astroquery=0.4
- authlib=0.15.3
- bokeh=2.2.3
- codecov==2.1.11
- cryptography==3.3.1
- django=3.1.7
- flake8=3.8.4
- inflection=0.5.1
- ipython=7.20.0
- jinja2=2.11.3
- jsonschema=3.2.0
- matplotlib=3.2.2
- nodejs=10.13.0
- numpy=1.18.5
- numpydoc=1.1.0
- pandas=1.2.2
- pip=20.3.3
- postgresql=12.2
- psycopg2=2.8.6
- pysiaf=0.9.0
- python=3.7.9
- pytest=6.2.2
- pytest-cov=2.11.1
- pyyaml=5.4.1
- scipy=1.6.1
- setuptools=52.0.0
- sphinx=3.5.1
- sqlalchemy=1.3.21
- twine=3.3.0
- wtforms=2.3.3
- pip:
  - asdf==2.7.1
  - crds==10.3.11
  - jwedb==0.0.6
  - jwst==1.1.0
  - pysqlite3==0.4.3
  - stsci_rtd_theme==0.0.2
  - git+https://github.com/spacetelescope/jwst_reffiles
