[tool.poetry]
name = "aio-apisession"
version = "0.1.10"
description = ""
authors = ["Sebastian Acuna <sebastian@unholster.com>"]
packages = [
    { include = "apisession" }
]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-xdist = "^2.3.0"
pytest-aiohttp = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
