
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T15:43:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d68064e936ad4bd36ae599e19f1450e88df24171",
 "version": "0.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
