[tool.poetry]
name = "hellofromchinmay"
version = "0.1.0"
description = ""
authors = ["chinmay <bhagyesh.deshmukh29@gmail.com>"]
packages = [{include="hellofromchinmay", from="src"}]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
