
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-02T17:39:31-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0701138dadac76743455869d2a93f8b7d13ae3de",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
