#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['updated_docs']

package_data = \
{'': ['*']}

setup(name='updated_docs',
      version='0.1.0',
      description='A package that checks whether you should update docs.',
      author=None,
      author_email='Mark Harvey <inspiredharvey@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.10',
     )
