name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pydata-factory
        channels: conda-forge
        environment-file: environment.yaml
        mamba-version: "*"

    - name: install dependencies
      run: python -m pip install -e .

    - name: show environment
      run: conda list

    - name: run tests
      run: python -m pytest -vv

    - name: pre-commit check
      run: pre-commit run --all-files
