
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-08T14:25:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa2de37400ce907dde9e5ce39c63cc40208e42ad",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
