[tool.poetry]
name = "high-order-layers-torch"
version = "1.0.3"
description = "High order layers in pytorch"
authors = ["jloverich <john.loverich@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.6"
torch = "*"
pytorch-lightning = "*"

[tool.poetry.dev-dependencies]
pbr = "*"
hydra-core = "*"
matplotlib = "*"
torchvision = "*"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
