
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T10:20:16+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc0965c205babfe9c386b6f6ae7255379bd9a9ea",
 "version": "v0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
