[tool.poetry]
name = "tscalcs"
version = "0.1.0_dev4"
description = "Package to operate time series math operations as if they were normal python variables."
authors = ["Pedro H. Thompson Furtado <thompsonp17@hotmail.com>"]
keywords = ["time series", "calculations", "algebric", "variable"]
readme = "README.md"
license = "MIT"
homepage = "https://codigo-externo.petrobras.com.br/simu/tscalcs"
repository = "https://codigo-externo.petrobras.com.br/simu/tscalcs"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = {extras = ["toml"], version = "^5.5"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["./tscalcs"]

