[tool.poetry]
name = "paccckcakdjasgegeg"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^56.0.0"
aiohttp = "^3.7.4"
colorama = "^0.4.4"
fortnitepy = "^3.4.0"
twine = "^3.4.1"
aioconsole = "^0.3.1"
flask = "^1.1.2"
sanic = "^21.3.2"
termcolor = "^1.1.0"
discord = "^1.0.1"
python-dotenv = "^0.17.0"
discord-webhook = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
