# -*- coding: utf-8 -*-
"""signal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mtNvJzcxi7jjMBmdCaF2os_XFGRSLGHA
"""
import numpy as np
import pandas as pd

class Signal:
  def __init__(self, data, above):
    self.data = data
    self.above = above
  def signals(self):
    signals = pd.DataFrame(index=self.data.index)
    signals = signals.sort_values(by='date')
    signals['signal'] = 0.0
    if self.above:
      signals['signal'] = np.where(self.data['close'] > self.data['VWAP'], 1.0, 0.0)
    else:
      signals['signal'] = np.where(self.data['close'] < self.data['VWAP'], 1.0, 0.0)
    signals['positions'] = signals['signal'].diff()
    signals =signals.dropna()
    return signals