
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T22:41:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6be5f47016d4c0e328fe7707f00cd28cd0172990",
 "version": "0.4.2b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
