# coding: utf-8

"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: main
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pds.api_client
from pds.api_client.api.bundles_collections_api import BundlesCollectionsApi  # noqa: E501
from pds.api_client.rest import ApiException


class TestBundlesCollectionsApi(unittest.TestCase):
    """BundlesCollectionsApi unit test stubs"""

    def setUp(self):
        self.api = pds.api_client.api.bundles_collections_api.BundlesCollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collections_of_a_bundle(self):
        """Test case for collections_of_a_bundle

        get collections belonging to a given bundle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
