# coding: utf-8

"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: main
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pds.api_client
from pds.api_client.models.metadata import Metadata  # noqa: E501
from pds.api_client.rest import ApiException

class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Metadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pds.api_client.models.metadata.Metadata()  # noqa: E501
        if include_optional :
            return Metadata(
                creation_date_time = '', 
                update_date_time = '', 
                version = '', 
                label_url = ''
            )
        else :
            return Metadata(
                label_url = '',
        )

    def testMetadata(self):
        """Test Metadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
