# coding: utf-8

"""
    Planetary Data System API

    Federated PDS API which provides actionable end points standardized between the different nodes.   # noqa: E501

    The version of the OpenAPI document: main
    Contact: pds-operator@jpl.nasa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pds.api_client
from pds.api_client.api.collections_api import CollectionsApi  # noqa: E501
from pds.api_client.rest import ApiException


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = pds.api_client.api.collections_api.CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_collections_by_lidvid(self):
        """Test case for collections_by_lidvid

        collections URN resolver for lidvid  # noqa: E501
        """
        pass

    def test_collections_by_lidvid_all(self):
        """Test case for collections_by_lidvid_all

        Get one collection by lidvid, or all versions of a collection by lid  # noqa: E501
        """
        pass

    def test_collections_by_lidvid_latest(self):
        """Test case for collections_by_lidvid_latest

        collections URN resolver for lidvid  # noqa: E501
        """
        pass

    def test_get_collection(self):
        """Test case for get_collection

        request PDS collections  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
