[package]
name = "python-calamine"
version = "0.0.3"
authors = ["Dmitriy <dimastbk@yandex.ru>"]
description = "Python binding for Rust's library for reading excel and odf file - calamine"
edition = "2018"
homepage = "https://github.com/dimastbk/python-calamine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dimastbk/python-calamine"

[lib]
name = "python_calamine"
crate-type = ["cdylib"]

[dependencies]
calamine = {version = "0.18.0", features = ["dates"] }
pyo3 = {version = "0.14.5", features = ["extension-module"] }
chrono = { version = "0.4.17", features = ["serde"] }

[build-dependencies]
pyo3-build-config = "^0.14"

[package.metadata.maturin]
python-source = "python"
