package:
  name: nexusformat
  version: "0.7.0"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v0.7.0

build:
  entry_points:
    - nxstack = nexusformat.scripts.nxstack:main
    - nxduplicate = nexusformat.scripts.nxduplicate:main
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
    - versioneer

  run:
    - python >=3.6
    - numpy >=1.16
    - h5py
    - versioneer

test:
  commands:
    - nexusformat --version
    - pytest

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
