# Generated by Django 3.2.5 on 2021-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_koldar_utils.django_toolbox.fields.ArrowField
import django_koldar_utils.django_toolbox.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_cbim_general_service', '0001_create_group_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserPermission',
            fields=[
                ('id',
                 models.BigAutoField(db_column='id', help_text='Unique Id representing the concept', primary_key=True,
                                     serialize=False)),
                ('user_id', models.BigIntegerField(db_column='user_id', default=None,
                                                   help_text='id of a user. The id are the one from the user authentication service')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                                 to='auth.permission')),
            ],
            options={
                'db_table': 'django_cbim_general_service.AuthUserPermission',
            },
        ),
    ]
