name: pygeoutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - nest-asyncio
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - shapely
  - urllib3

  # pygeoutils deps
  - dask
  - geopandas
  - netcdf4
  - numpy
  - rasterio>=1.2
  - xarray

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - pytest
  - pytest-clarity
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - psutil
  - toml

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
