import re
from datazen.parsing import merge as merge
from datazen.paths import advance_dict_by_path as advance_dict_by_path, format_resolve_delims as format_resolve_delims, unflatten_dict as unflatten_dict
from typing import Dict, List, Tuple

KW_OPEN: str
KW_CLOSE: str
KW_PATTERN: str

def target_is_literal(name: str) -> bool: ...
def parse_target(name: str) -> Tuple[re.Pattern, List[str]]: ...
def parse_targets(targets: List[dict]) -> Tuple[Dict[str, dict], Dict[str, dict]]: ...
def match_target(name: str, pattern: re.Pattern, keys: List[str]) -> Tuple[bool, Dict[str, str]]: ...
def resolve_target_list(target_list: list, match_data: Dict[str, str]) -> list: ...
def resolve_dep_data(entry: dict, data: dict) -> dict: ...
def resolve_target_data(target_data: dict, match_data: Dict[str, str]) -> dict: ...
