
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T08:47:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bac49962ae79a2d146677f12bbec4399b409c62",
 "version": "2.8.9.post0.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
