[tool.poetry]
name = "mocksey"
version = "0.4.0"
description = "Stupidly-simple python mocking utility with moxie."
authors = ["Chris McGraw <mitgr81+mocksey@mitgr81.com>"]
repository = "https://github.com/mitgr81/mocksey"
license = "MIT"
readme = "README.rst"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Testing",
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[tool.black]
line-length    = 120
target_version = ['py38']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
