---
format_version: "1.0"
revision: 
    date: "2017-11-30"
    authors: 
        - $ref: "authors/Wayne_Crawford.author.yaml#author"
sensor:
    
    equipment:
        model: "DPG"
        type: "Differential Pressure Gauge"
        description: "Differential Pressure Gauge"
        manufacturer: "various"
        vendor: "various"
    seed_codes:
        band_base: "B"
        instrument: "D"

    response_stages:
        - $ref: "sensors/responses/SIO-LDEO_DPG_generic_theoretical.stage.yaml#stage"
    configuration_default: "generic"
    configuration_definitions:
        "5004": 
            equipment: {manufacturer: "SIO"}
            response_stages: 
                - $ref: "sensors/responses/SIO-LDEO_DPG_5004_calibrated.stage.yaml#stage"
        "5018":
            equipment: {manufacturer: "SIO"}
            response_stages:
                - $ref: "sensors/responses/SIO-LDEO_DPG_5018_calibrated.stage.yaml#stage"
        "5027":
            equipment: {manufacturer: "SIO"}
        "generic":
            equipment: {manufacturer: "unknown"}
        "IP004":
            equipment: {manufacturer: "IPGP"}
        "IP005":
            equipment: {manufacturer: "IPGP"}
        "IP006":
            equipment: {manufacturer: "IPGP"}
        "IP007":
            equipment: {manufacturer: "IPGP"}
        "LD013":
            equipment: {manufacturer: "LDEO"}
        "LDxxx":
            equipment: 
                manufacturer: "LDEO"
                description: "DPG on lost BBOBS9, did not note serial number"
                
notes: 
    - "dip value assumes pressure gauge positive correponds to increasing pressure in upward compressional wave (seafloor up => pressure up)"
    - "orientation H=hydrophone, F=infrasound.  Which to use?"
