
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T16:33:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "14bf5d118c717a548788584f32251797d25e80ae",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
