# Generated by Django 3.2.5 on 2021-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion
import django_koldar_utils.django_toolbox.fields.ArrowField
import django_koldar_utils.django_toolbox.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_cbim_general_service', '0000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(db_column='id', help_text='Unique Id representing the concept', primary_key=True, serialize=False)),
                ('group_id', models.BigIntegerField(db_column='group_id', default=None, help_text='id of a group. The id are the same one from the user authentication service')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.permission')),
            ],
            options={
                'db_table': 'django_cbim_general_service.GroupPermission',
            },
        ),
    ]
