# Generated by Django 3.2.4 on 2021-06-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cbim_general_service', "0002_create_user_permissions"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # disable checks
                # f"SET FOREIGN_KEY_CHECKS=0;",
                # drop the relationship of user-group, since it is managed by the user-auth-service
                f"DROP TABLE IF EXISTS auth_user_groups CASCADE;",
                # We need user-permissions and group-permission to be first citizen, so we remove them as well
                f"DROP TABLE IF EXISTS auth_user_user_permissions CASCADE;",
                f"DROP TABLE IF EXISTS auth_group_permissions CASCADE;",
                # drop auth user and group tables, since we don't want to have them
                f"DROP TABLE IF EXISTS auth_user CASCADE;",
                f"DROP TABLE IF EXISTS auth_group CASCADE;",
                # drop the AuthUser (which is normally an alias of user if django-koldar-utils has been used)
                #f"DROP TABLE IF EXISTS user_auth_service.AuthUser CASCADE;",
                #f"DROP TABLE IF EXISTS user_auth_service.AuthUser_groups CASCADE;",
                #f"DROP TABLE IF EXISTS user_auth_service.AuthUser_user_permissions CASCADE;",
                # reenable checks
                # f"SET FOREIGN_KEY_CHECKS=1;",
            ],
        ),
    ]
