[tool.poetry]
name = "tiny_algos"
version = "0.1.1"
description = "A compact modules for Data Structures and Algorithms"
authors = ["azriel1rf <azriel.1rf@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
