# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V7DnYF5YjWb0aT_58QFThVw-AhL42DCH
"""

import pathlib
from setuptools import setup, find_packages
# The directory containing this file
HERE = pathlib.Path(__file__).parent
# The text of the README file
README = (HERE / "README.md").read_text()
# This call to setup() does all the work
setup(
name="sentiment_algorithm",
version="1.0.2",
description="This package use newsreader algorithm to produce buy and sell signals, portfolio, ROI and sharpe ratio for stock #AAPL",
long_description=README,
long_description_content_type="text/markdown",

author="Jiayi Li",
author_email="jl884@duke.edu",
license="MIT",
classifiers=[
"License :: OSI Approved :: MIT License",
"Programming Language :: Python :: 3",
"Programming Language :: Python :: 3.7",
],
packages=find_packages(),
# dependencies for installing the package
install_requires=["numpy", "pandas","snscrape","yfinance", "pyspark","matplotlib","nltk","vaderSentiment","seaborn","scipy", "pathlib", "setuptools","matplotlib", "Cython"]
)