[tool.poetry]
name = "vretcity"
version = "0.1.1"
description = "Package to preprocess and analyse data from the vretcity project at NUDZ"
authors = ["Lukáš Hejtmánek <hejtmy@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
plotly = "^5.3.1"
pandas = "^1.3.3"
numpy = "^1.20.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
