
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T17:25:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "421aa83f435fb34d30ff1e41d5be6acc60b90d0a",
 "version": "2.0.0a15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
