[tool.poetry]
name = "first-poet-lib"
version = "0.1.0"
description = ""
authors = ["jagadeesh32 <katla.jagadeesh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.20.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
