from typing import Any

class DataCache:
    data: Any
    loaded: Any
    cache_dir: Any
    def __init__(self, cache_dir: str) -> None: ...
    def load(self, directory: str) -> None: ...
    def write(self) -> None: ...
    def clean(self) -> None: ...
