[tool.poetry]
name = "aiojarm"
version = "0.2.2"
description = "Async JARM client"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
aiometer = "^0.3.0"
importlib-metadata = {version = "^4.8.1", python = "<3.8"}
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
autopep8 = "^1.5.7"
black = "^21.9b0"
coverage = "^5.5"
coveralls = "^3.2"
flake8 = "^3.8.4"
isort = "^5.9.3"
mypy = "^0.910"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
pyupgrade = "^2.29.0"

[tool.poetry.scripts]
aiojarm = "aiojarm.cli:main_wrapper"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = []
line_length = 88
multi_line_output = 3
use_parentheses= true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
