from typing import List, Tuple
from vtelem.channel import Channel as Channel, ChannelEncoder as ChannelEncoder
from vtelem.enums.primitive import Primitive as Primitive
from vtelem.registry import Registry as Registry

class ChannelRegistry(Registry[Channel]):
    def __init__(self, initial_channels: List[Channel] = ...) -> None: ...
    def get_channel_type(self, chan_id: int) -> Primitive: ...
    def add_channel(self, channel: Channel) -> Tuple[bool, int]: ...
    def describe(self, indented: bool = ...) -> str: ...
