[tool.poetry]
name = "aioxmlrpc"
version = "0.6.0"
description = "Source code of Sequoia API TLDPublic"
homepage = "https://github.com/mardiros/aioxmlrpc"
license = "BSD-3-Clause License"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]


[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.19.0"


[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"