[project]
name = "cyberbrain"
version = "0.2.3"
description = "Python debugging, redefined."
requires-python = ">=3.7,<3.10"
dynamic = [ "classifiers",]
readme = "README.md"
keywords = [ "debugging", "debugger", "visualization",]
dependencies = [ "pygments<3.0.0,>=2.6.1", "crayons<1.0.0,>=0.3.0", "shortuuid<2.0.0,>=1.0.1", "attrs<21.0.0,>=20.0.0", "get-port<1.0.0,>=0.0.5", "typing-extensions<4.0.0,>=3.7.4", "more-itertools<9.0.0,>=8.5.0", "cheap-repr<1.0.0,>=0.4.2", "ujson==4.1.0", "jsonpickle<2.0.0,>=1.4.1", "portpicker<2.0.0,>=1.3.1", "msgpack<2.0.0,>=1.0.2", "requests<3.0.0,>=2.25.1",]
[[project.authors]]
name = "laike9m"
email = "laike9m@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
Funding = "https://github.com/sponsors/laike9m"
"Bug Tracker" = "https://github.com/laike9m/Cyberbrain/issues"
homepage = "https://github.com/laike9m/Cyberbrain"
repository = "https://github.com/laike9m/Cyberbrain"

[project.optional-dependencies]
extra_tests = [ "numpy==1.18", "pandas==1.1.3",]

[tool.pdm.dev-dependencies]
dev = [ "tox<4.0,>=3.14", "tox-pdm~=0.3", "pytest-xdist<2.0,>=1.31", "pytest<7.0.0,>=6.0.1", "pyhamcrest<3.0.0,>=2.0.2", "responses<1.0.0,>=0.12.1", "detect<2021.0.0,>=2020.7.1", "bytecode<1.0.0,>=0.11.0", "ptpython<4.0.0,>=3.0.7", "pdir2<1.0.0,>=0.3.1", "tox-gh-actions~=2.8", "twine~=3.4",]

[tool.pylint.messages_control]
disable = "bad-continuation,attribute-defined-outside-init,W0511,R0902,R0913,W0622,C0116,C0103,\nR0903,W0631,W0212,W0603,R1710,R0201\n"

[tool.pytest.ini_options]
testpaths = [ "test",]
norecursedirs = [ "cyberbrain-vsc*", ".vscode", "*.egg",]
