[tool.poetry]
name = "Morpion"
version = "0.3.10"
description = "A nice Morpion game"
authors = ["PetchouHelper <petchou91d@gmail.com>"]
packages = [
    { include = "Morpion" },
]

[tool.poetry.dependencies]
python = "^3.9"

termcolor = "^1.1.0"
art = "^5.2"
winshell = "^0.6"
requests = "^2.26.0"
pypiwin32 = "^0.1"
pywin32 = "^0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
