
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T13:40:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe5c6853128020aaaa59b440cc5203b940dcd39a",
 "version": "0.28.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
