[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
author = "Yandex Research"
author-email = "strausmg@gmail.com"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dist-name = "rtdl"
home-page = "https://github.com/yandex-research/rtdl"
keywords = "deep learning, artificial intelligence, research, library, python, pytorch, torch"
module = "rtdl"
requires = [
    "numpy >=1.17,<2",
    "torch >= 1.6,<2",
]
requires-python = ">=3.7"

[tool.black]
exclude = "node"
skip_string_normalization = true

[tool.flit.sdist]
exclude = ["bin", "lib", "output", "requirements.txt"]

[tool.isort]
skip = ["node"]
profile = "black"
multi_line_output = 3
known_first_party = ["rtdl" ,"lib"]
