#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rtdl', 'rtdl.tests']

package_data = \
{'': ['*']}

install_requires = \
['numpy >=1.17,<2', 'torch >= 1.6,<2']

setup(name='rtdl',
      version='0.0.7',
      description='Revisiting Tabular Deep Learning.',
      author='Yandex Research',
      author_email='strausmg@gmail.com',
      url='https://github.com/yandex-research/rtdl',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
