
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T11:10:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16a963524607faf9665347c784b0a3b46a2a631d",
 "version": "0.7.1.post.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
