[tool.poetry]
name = "pyictacp"
version = "0.2.2"
description = "ICT Protege Automation and Control Protocol wrapper"
authors = ["Thomas Hobson <git@hexf.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
