- project:
    templates:
      - openstack-python3-xena-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstack-lower-constraints-jobs
      - openstack-cover-jobs
