#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='text2midi',
      version='0.0.1',
      description='text2midi',
      author='Nishkrit Desai',
      author_email='nishkritdesai10@gmail.com',
      url='https://github.com/nshdesai/text2midi',
      py_modules=['text2midi'],
     )
