
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T10:27:07-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7de5f4e0aac0dbe6bbe8d6a9703c4f526a74b3e",
 "version": "1.88.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
