# Generated by Django 3.1.7 on 2021-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeeditor', '0003_auto_20210610_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
