[tool.poetry]
name = "textalytics-python-client"
version = "0.1.1"
description = "python client to interface with textalytics hosted nlp service"
authors = ["Manoj Bharadwaj <manoj@cloudcosmos.tech>"]
license = "MIT"

packages = [
    { include="textalytics_client", from="." },
]

[tool.poetry.dependencies]
python = "^3.8"
textalytics-core = "^0.1.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
path = "./venv"

[tool.poetry.scripts]
test = 'scripts:test'

