
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T15:12:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f984d5925fad055b8ffdd233c6d25d19f948e60",
 "version": "0.8.15a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
