channels:
- defaults
dependencies:
- astropy==4.3.1
- bokeh=2.3.3
- codecov==2.1.11
- cryptography==3.4.7
- django=3.1.7
- flake8=3.9.2
- inflection=0.5.1
- ipython=7.22.0
- jinja2=3.0.1
- jsonschema=3.2.0
- matplotlib=3.3.4
- nodejs=10.13.0
- numpy=1.20.1
- numpydoc=1.1.0
- pandas=1.3.2
- pip=21.0.1
- postgresql=12.2
- psycopg2=2.8.6
- pytest=6.2.3
- pytest-cov=2.12.1
- python=3.7.10
- pyyaml=5.4.1
- scipy=1.7.1
- setuptools=52.0.0
- sphinx=4.0.2
- sqlalchemy=1.4.22
- twine=3.3.0
- wtforms=2.3.3
- pip:
  - asdf==2.8.1
  - astroquery==0.4.3
  - crds==11.0.4
  - jwedb==0.0.6
  - jwst==1.3.0
  - pysiaf==0.11.0
  - pysqlite3==0.4.3
  - stdatamodels==0.2.3
  - stsci_rtd_theme==0.0.2
  - git+https://github.com/spacetelescope/jwst_reffiles
  