---
minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Local Hooks ----------------------------------------------------------------------------------------------->
  - repo: local
    hooks:
      - id: sort-pylint-spelling-words
        name: Sort PyLint Spelling Words File
        entry: python .pre-commit-hooks/sort-pylint-spelling-words.py
        language: system
        files: ^\.pylint-spelling-words$

      - id: check-changelog-entries
        name: Check Changelog Entries
        entry: python .pre-commit-hooks/check-changelog-entries.py
        language: system
  # <---- Local Hooks ------------------------------------------------------------------------------------------------

  # ----- Formatting ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.5+
        args: [--py3-plus]
        exclude: (^src/pytestskipmarkers/utils/saltext/.*\.py)

  - repo: https://github.com/hakancelik96/unimport
    rev: "0.9.2"
    hooks:
      - id: unimport
        name: Remove unused imports
        args: [--remove]
        exclude: ^(docs/.*\.py|src/pytestskipmarkers/(cli|daemons)/__init__\.py)$

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py3-plus,
          --application-directories=.:src:examples/echo-extension/src
        ]
        exclude: src/pytestskipmarkers/version.py

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/pytestskipmarkers/version.py

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/pytestskipmarkers/.*\.py)$
        additional_dependencies: [black==21.9b0]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        name: PyLint
        args: [--output-format=parseable, --rcfile=.pylintrc]
        exclude: src/pytestskipmarkers/version.py
        additional_dependencies:
          - pyenchant

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: ^(src/|tests/).*\.py$
        args: []
        additional_dependencies:
          - types-attrs
          - types-setuptools
  # <---- Formatting -------------------------------------------------------------------------------------------------

  # ----- Security -------------------------------------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against Salt
        args: [--silent, -lll, --skip, B701]
        exclude: >
            (?x)^(
                tests/.*
            )$
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security ---------------------------------------------------------------------------------------------------
