name: pyseaflux-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - pytest
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - ipython
  - nbconvert
  - nbformat
  - ipykernel
  - pandoc
  - pip
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
    - pooch
    - PyCO2SYS
    - docrep<=0.2.7
    - nbsphinx
    - fetch-data
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - recommonmark
