
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T12:15:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e90b2420e77387c207a7ba80847c4e8ee1ebc48",
 "version": "0.8.15a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
