
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T16:54:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8313173b8c9930290c519313d9a2f53d4674b1c3",
 "version": "0.28.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
