from setuptools import setup

setup(name='pizaa', version=0.28, description='Python image to ascii-art library', packages=['pizaa'], author_email='mrtnb1998@gmail.com', zip_safe=False, author='Kollob', install_requires=['pillow'], long_description='''A python image to ascii art library.
Its usage is simple:

itaa(img[, rescale, mode, output, use_spaces, invert, enlarge]): image to ascii art function. If mode is 'save' save's text to output, else returns it

_itaa(img[, rescale, mode, output, invert, enlarge]): old itaa function, with old 25 symbols pallete (new one have 51 symbols)

restore_grayscale(img[, output]): restores grayscale from text, generated by itaa function''', long_description_content_type='text/markdown')
