#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yaqd_rgb', 'yaqd_rgb.rgbdriverkit']

package_data = \
{'': ['*']}

install_requires = \
['numpy', 'pyusb', 'yaqd-core>=2020.06.3']

extras_require = \
{'dev': ['black', 'pre-commit']}

entry_points = \
{'console_scripts': ['yaqd-rgb-qmini = yaqd_rgb._rgb_qmini:RGBQmini.main']}

setup(name='yaqd-rgb',
      version='2021.10.0',
      description='yaq daemons for RGB Photonics hardware',
      author='yaq Developers',
      author_email='git@ksunden.space',
      url='https://yaq.fyi',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
