[tool.poetry]
name = "primapy-koffing"
version = "0.0.1"
description = "Safety placeholder"
authors = ["AMOps <amops@prima.it>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
