
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T22:34:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "24f778b495b273f0a26bdd2230a7e923fbda07a0",
 "version": "0.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
