
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-01T08:29:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9204b8acfcdde4d1d47b356d17d3aa80a1fbc3d2",
 "version": "0.18rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
