from typing import Any
from vtelem.channel.registry import ChannelRegistry as ChannelRegistry
from vtelem.classes import DEFAULTS as DEFAULTS
from vtelem.classes.byte_buffer import ByteBuffer as ByteBuffer
from vtelem.frame.fields import MESSAGE_FIELDS as MESSAGE_FIELDS
from vtelem.types.frame import FrameHeader as FrameHeader

LOG: Any

def parse_invalid_frame(header: FrameHeader, buf: ByteBuffer, ___: ChannelRegistry) -> dict: ...
def parse_data_frame(header: FrameHeader, buf: ByteBuffer, registry: ChannelRegistry) -> dict: ...
def parse_event_frame(header: FrameHeader, buf: ByteBuffer, registry: ChannelRegistry) -> dict: ...
def parse_message_frame(header: FrameHeader, buf: ByteBuffer, _: ChannelRegistry) -> dict: ...
def parse_stream_frame(header: FrameHeader, buf: ByteBuffer, registry: ChannelRegistry) -> dict: ...
