- project:
    templates:
      - openstack-lower-constraints-jobs-neutron
      - openstack-python3-xena-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
