#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['oktools', 'oktools.tests.data.three_girls.tests']

package_data = \
{'': ['*'],
 'oktools': ['tests/*',
             'tests/data/*',
             'tests/data/empty_dir/*',
             'tests/data/exercise_dir/*',
             'tests/data/three_girls/*']}

install_requires = \
['gradools', 'rmdex', 'rnbgrader>=0.2']

entry_points = \
{'console_scripts': ['okt-dir2exercise = oktools.dir2exercise:main']}

setup(name='oktools',
      version='0.0.1a1',
      description='OKtools package',
      author='Matthew Brett',
      author_email='matthew.brett@gmail.com',
      url='https://github.com/matthew-brett/oktools',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
