
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T19:12:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec0309a8a5b46308b4bc6bff4fcd1d9746a85b82",
 "version": "0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
