
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T11:52:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cbb58376df120d5439c9de1020324d20fc31d02",
 "version": "0.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
