[build-system]
requires = [
    "setuptools >= 58",
    "setuptools_scm[toml] >= 6",
    "wheel >= 0.37",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/jomiel_kore/__init__.py"
write_to_template = "__version__ = {version!r}"

[tool.black]
target-version = ['py38']
line-length = 72
exclude = '''   # exclude common dirs
(
    /(
        examples
        \.git
        \.tox
    )/
)
'''
