
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-10T14:48:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7978909a48139950f981ea76524734c20d58f40",
 "version": "0.13.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
