
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-08T15:20:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe6ff8cc0235bf06a26a059a190a417f1ccc3962",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
