
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-05T21:44:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "74d53ba3430d3d7b3b26a7576d4ba60c543f4802",
 "version": "0.0.78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
