
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T19:11:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "69c6293e9ba949bdaf692417dc9bb405cdab9b46",
 "version": "0.0.79"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
