[tool.poetry]
name = "ml_models"
version = "0.1.6"
description = " This project is based upon basic ml-model testing and building a table."
readme="README.md"
authors = ["addyR <adarsharegmi121@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sklearn = "^0.0"
pandas = "^1.3.3"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
cli = "ml_models.console.console:main"
app = "ml_models.driver.main:main"