
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-08T08:15:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "786c5cd7ecc24a621c849704d436738fe5556eb4",
 "version": "2.8.9.post0.dev17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
