
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-06T11:51:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbca2f933abdc8b6aaffad342d8fd74f7450be5e",
 "version": "1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
