[tool.poetry]
name = "dwnld"
version = "0.2.1"
description = "A multiprotocol downloader"
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage= "https://github.com/4thel00z/dwnld"
packages = [
    { include = "libdwnld" },
    { include = "dwnld" },
]


[tool.poetry.dependencies]
python = "^3.7"
scp = "^0.13.6"
plumbum = "^1.7.0"
requests = "^2.26.0"
torpy = {extras = ["requests"], version = "^1.1.6"}

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"
neovim = "^0.3.1"
ptpython = "^3.0.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
