
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T12:12:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6fe4bb608cd227cb35c79272460cf4b33cb8f19",
 "version": "0.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
