[tool.isort]
profile = "black"

[tool.poetry]
name = "cli-ui"
version = "0.15.2"
description = "Build Nice User Interfaces In The Terminal"
readme = "README.rst"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
license = "BSD-3-Clause"
repository = "https://github.com/dmerejkowsky/python-cli-ui"
documentation = "https://dmerejkowsky.github.io/python-cli-ui/"

[tool.poetry.urls]
Changelog = "https://dmerejkowsky.github.io/python-cli-ui/changelog.html"
Issues = "https://github.com/dmerejkowsky/python-cli-ui/issues"

[tool.poetry.dependencies]
# Keep this in sync with .github/workflows/
python = "^3.6"
colorama = "^0.4.1"
tabulate = "^0.8.3"
unidecode = "^1.0.23"

[tool.poetry.dev-dependencies]
# Task runner
invoke = "^1.5.0"

# Tests
coverage = "^5.2"
pytest = "^6.2.1"
pytest-cov = "^2.10"

# Linters
black = { version = "21.8b0", python = ">=3.7" }
flake8 = "3.9.2"
flake8-bugbear = "^21.4.3"
flake8-comprehensions = "^3.4.0"
pep8-naming = "^0.11.1"
isort = "^5.7.0"
types-tabulate = "^0.1.0"
mypy = "0.900"

# Deps scanning
safety = "^1.9.0"

# Documentation
sphinx  = "^4.1.2"
sphinx-autobuild = "2021.3.14"
ghp-import = "^0.5.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
