
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T11:17:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e727390a364067c36c755994a98d0ba382d3cfe",
 "version": "0.9.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
