
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-04T10:53:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "474f3f7c0e18e3f8d3a8410b9ea59d4d679b389f",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
