[tool.poetry]
name = "s3-parse-url"
version = "0.1.0"
description = ""
authors = [
    "Mikhail Porokhovnichenko <marazmiki@gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.7 || ^3.8 || ^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-isort = "^2.0.0"
pytest-flake8 = "^1.0.7"
aioboto3 = "^9.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
