[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "reducto"
author = "Agustín Piqueres"
author-email = "agustin.piqueres@gmail.com"
home-page = "https://github.com/plaguss/reducto"
requires-python=">=3.8"
license = "MIT"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8"
]
description-file = "README.md"

[tool.flit.metadata.requires-extra]
test = [
    "pytest==6.2.3",
    "pytest-cov==2.11.1"
]
doc = [
    "sphinx",
    "sphinx-rtd-theme"
]
dev = [
    "black",
    "mypy",
    "types-tabulate==0.8.2",
    "tabulate==0.8.9"
]
tabulate = ["tabulate==0.8.9"]

[tool.flit.metadata.urls]
Documentation = "https://reducto.readthedocs.io"
Repository = "https://github.com/plaguss/reducto"

[tool.flit.scripts]
reducto = "reducto:main"