#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['reducto']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['black', 'mypy', 'types-tabulate==0.8.2', 'tabulate==0.8.9'],
 'doc': ['sphinx', 'sphinx-rtd-theme'],
 'tabulate': ['tabulate==0.8.9'],
 'test': ['pytest==6.2.3', 'pytest-cov==2.11.1']}

entry_points = \
{'console_scripts': ['reducto = reducto:main']}

setup(name='reducto',
      version='1.0.2',
      description='Reduce a package as a set of basic source code statistics. ',
      author='Agustín Piqueres',
      author_email='agustin.piqueres@gmail.com',
      url='https://github.com/plaguss/reducto',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.8',
     )
