
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-10T12:20:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3b212ea835b97196ad07adf38ec5dc7db6e3eab",
 "version": "1.21.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
