#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yaml2xbel']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='yaml2xbel',
      version='0.0.1',
      description='XBEL generator from YAML',
      author=None,
      author_email='Ngô Ngọc Đức Huy <huyngo@disroot.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
     )
