[tool.poetry]
name = "valoff_ie_api"
version = "0.1.0"
description = "An unofficial Python API for the Valuation Office REST API"
authors = ["Rowan Molony <rowan.molony@codema.ie>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1 || ^3.7"
loguru = "^0.5.3"
icontract = "^2.5.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
