
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-09T16:38:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "227d84ea8ebe932ef91e58d2ceb02f2a936d38d7",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
